// styled
import "@/app/_style/globals.css";
// services
import { Poppins, Sono } from "next/font/google";
import Providers from "@/app/providers";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const sono = Sono({
  variable: "--font-sono",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  display: "swap",
});

export const metadata = {
  title: {
    default: "The Wild Oasis",
    template: "%s | The Wild Oasis",
  },
  description: "Generated by Vinicius Moreira",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${sono.variable} antialiased h-screen`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
